INSERT INTO JOURNAL(JOURNAL_ID, JOURNAL_RATING, JOURNAL_TITLE) VALUES (1, 1, 'Information, Communication and Society');
INSERT INTO JOURNAL(JOURNAL_ID, JOURNAL_RATING, JOURNAL_TITLE) VALUES (2, 2, 'Bioethica Forum');
INSERT INTO JOURNAL(JOURNAL_ID, JOURNAL_RATING, JOURNAL_TITLE) VALUES (3, 1, 'What the heck');